name: "✋ 질문/건의사항"
description: "궁금한 점이나 건의사항이 있으시다면"
labels:
  - ":hand: 질문/건의사항"

body:
  - id: content
    type: textarea
    validations:
      required: true
    attributes:
      label: "✋ 질문/건의사항"
      description: 이곳에 질문이나 건의사항을 남겨주새요!